server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: Umid/4709.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mongodb:
    uri: mongodb://localhost:27017/user_logs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/