server:
  port: 8084

spring:
  application:
    name: ai-integration-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_db
    username: postgres
    password: Umid/4709.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: YOUR_REAL_API_KEY